### ISSUE TITLE
LevelLoader freeing StartLevel at game start

### ISSUE THREAD

**Issue by henriiquecampos** [GDQuest/godot-platformer-2d#176]
**I'm submitting a...**

- [x] Bug report.
- [ ] Feature request.

## Bug report ##

**What is the current behavior?**
LevelLoader is `queue_free`ing the StartLevel set by the `Game` when the game starts.

**What is the expected behavior?**
LevelLoader should only `queue_free` the previous level if any.

**Tell us the steps to reproduce the bug, and if possible share a minimal demo of the problem.** 

1. Add a breapoint to `LevelLoader:23` 
2. Add a `PackedScene`, e.g. `Level1.tscn`, to `Game` node in `Game.tscn`
3. Start the game

**Comment by NathanLovato** [comment]
Thanks. Note that for small bugs, if you're going to fix it yourself, or in the team, you don't need to use the template. If you find a small reproducible bug like that, that just requires changing a line of code or two, you can fix it straight away, as it'll likely take you less time than opening an issue.

Or if we decide to use tickets for everything, a one-line description of the problem is enough, and you can fix the bug straight away as well. It's mostly for tasks that would take hours of work that I prefer to have an issue, mostly because of budget.
